# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78f930b50be8b222c00dd62a15dcb3e7e7c06458a0912e75cc42766729c91ffc20e17edfc3093a51d81c62dd967fe03017e02d20b74c457d5bae3f7dacdf85bf

test:
  secret_key_base: 102e2c6891dea39faeec387a94636252ffa7fc2c132d508b3d9f73a9430face6fa8a92f5ab7b34a9d5d687e8e802b7e635e3066e94ee13d0effa34fd3371d502

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
